version: '3.8'

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    environment:
      - LITELLM_MASTER_KEY=sk-1234
      - LITELLM_SALT_KEY=sk-1234
      - DATABASE_URL=postgresql://user:password@postgres:5432/litellm_db
    depends_on:
      - postgres
    command: ["--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge