version: '3.8'

services:
  chroma-db:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma
    environment:
      - IS_PERSISTENT=TRUE
    networks:
      - app-network

volumes:
  chroma_data:

networks:
  app-network:
    driver: bridge